module.exports = {
    "annotation.png": require("./app/img/annotation.png"),
    "bongshin.png": require("./app/img/bongshin.png"),
    "caption.png": require("./app/img/caption.png"),
    "categories.png": require("./app/img/categories.png"),
    "check.png": require("./app/img/check.png"),
    "clear.png": require("./app/img/clear.png"),
    "close.png": require("./app/img/close.png"),
    "csv.png": require("./app/img/csv.png"),
    "delete.png": require("./app/img/delete.png"),
    "demo.png": require("./app/img/demo.png"),
    "demo_story.png": require("./app/img/demo_story.png"),
    "dims.png": require("./app/img/dims.png"),
    "draw.png": require("./app/img/draw.png"),
    "empires.png": require("./app/img/empires.png"),
    "expand.png": require("./app/img/expand.png"),
    "export.png": require("./app/img/export.png"),
    "facets.png": require("./app/img/facets.png"),
    // "favicon.ico": require("./app/img/favicon.ico"),
    "filter.png": require("./app/img/filter.png"),
    "gdocs.png": require("./app/img/gdocs.png"),
    "gif.png": require("./app/img/gif.png"),
    "hide.png": require("./app/img/hide.png"),
    "highlight.png": require("./app/img/highlight.png"),
    "image.png": require("./app/img/image.png"),
    "info.png": require("./app/img/info.png"),
    "json.png": require("./app/img/json.png"),
    "l-fac.png": require("./app/img/l-fac.png"),
    "l-seg.png": require("./app/img/l-seg.png"),
    "l-uni.png": require("./app/img/l-uni.png"),
    "load.png": require("./app/img/load.png"),
    "mail.png": require("./app/img/mail.png"),
    "matt.png": require("./app/img/matt.png"),
    "menu.png": require("./app/img/menu.png"),
    "min.png": require("./app/img/min.png"),
    "ms-logo.svg": require("./app/img/ms-logo.svg"),
    "nathalie.png": require("./app/img/nathalie.png"),
    "next.png": require("./app/img/next.png"),
    "open.png": require("./app/img/open.png"),
    "pin.png": require("./app/img/pin.png"),
    "play.png": require("./app/img/play.png"),
    "png.png": require("./app/img/png.png"),
    // "presidents.png": require("./app/img/presidents.png"),
    "prev.png": require("./app/img/prev.png"),
    "q.png": require("./app/img/q.png"),
    "r-arb.png": require("./app/img/r-arb.png"),
    "r-cal.png": require("./app/img/r-cal.png"),
    "r-grid.png": require("./app/img/r-grid.png"),
    "r-lin.png": require("./app/img/r-lin.png"),
    "r-rad.png": require("./app/img/r-rad.png"),
    "r-spi.png": require("./app/img/r-spi.png"),
    "record.png": require("./app/img/record.png"),
    "reset.png": require("./app/img/reset.png"),
    "s-chron.png": require("./app/img/s-chron.png"),
    "s-intdur.png": require("./app/img/s-intdur.png"),
    "s-log.png": require("./app/img/s-log.png"),
    "s-rel.png": require("./app/img/s-rel.png"),
    "s-seq.png": require("./app/img/s-seq.png"),
    "segments.png": require("./app/img/segments.png"),
    "story.png": require("./app/img/story.png"),
    "svg.png": require("./app/img/svg.png"),
    "timeline.png": require("./app/img/timeline.png"),
    // "ui-640.png": require("./app/img/ui-640.png"),
    // "ui.png": require("./app/img/ui.png"),
    "vl.png": require("./app/img/vl.png"),
    // "war.png": require("./app/img/war.png"),
};